Fixed missing documentation

diff --git a/docs/makedox b/docs/makedox
--- a/docs/makedox
+++ b/docs/makedox
@@ -1,5 +1,16 @@
 #!/bin/bash
 
+if [[ -z "${MRB_SOURCE}" ]]; then
+    echo "MRB_SOURCE was not set!"
+    exit 1
+fi
+
+DOCS_PATH=$MRB_SOURCE/ubcc1pi/docs/
+if [ ! -d $DOCS_PATH ]; then
+    echo "Can't find the documentation directory: ${DOCS_PATH}"
+    exit 2
+fi
+
 echo "Checking documentation for issues"
 
 # Run doxygen in a "strict mode" to ensure that everything is documented, this won't actually produce any documentation but will put any issues in warnings.txt
@@ -12,7 +23,8 @@ doxygen Doxyfile &> /dev/null
 N_ISSUES=`wc -l warnings.txt | cut -d ' ' -f 1`
 if [ $N_ISSUES -eq 0 ]; then
     echo; echo "No issues found! Safe to push :)"
-    return
+    rm -rf validation
+    exit 0
 fi
 echo; echo "There were $N_ISSUES issues with the documentation :("
 echo "Press any key for more details..."
@@ -26,10 +38,10 @@ while read LINE; do
     ISSUE=`echo $LINE | cut -d ':' -f 4-`
 
     echo; echo "Issue $COUNTER: $ISSUE"
-    echo $FILE
-    echo "Line $NUM"
+    echo "vim +$NUM $FILE"
 
     COUNTER=$(($COUNTER + 1))
 done < warnings.txt
 
 echo; echo "^^^ Please fix the above issues before pushing code ^^^"
+rm -rf validation
